macro(return_if_not_target)
	foreach(target ${ARGV})
		message("target=${target}")
		if( NOT TARGET ${target})
			message("NOT building ${CMAKE_CURRENT_SOURCE_DIR}. Target not found: ${target}")
			return()
		endif()
	endforeach()
endmacro()

macro(return_if)
	if (${ARGV})
		message("NOT building ${CMAKE_CURRENT_SOURCE_DIR}.")
		return()
	endif()
endmacro()
